name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install Frontend Dependencies
      run: |
        npm install
        npm install -D @vitejs/plugin-react-swc
    
    - name: Build Frontend
      run: |
        npm run build
      env:
        CI: false
        NODE_ENV: production
    
    - name: Install Backend Dependencies
      run: |
        cd backend
        npm install
    
    - name: Build Backend
      run: |
        cd backend
        npm run build
      env:
        NODE_ENV: production
    
    - name: Upload Frontend Build
      uses: actions/upload-artifact@v3
      with:
        name: frontend-build
        path: dist/
    
    - name: Upload Backend Build
      uses: actions/upload-artifact@v3
      with:
        name: backend-build
        path: backend/dist/ 