name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Dependencies
      run: |
        cd backend
        npm install
    
    - name: Build Backend
      run: |
        cd backend
        npm run build
      env:
        NODE_ENV: production
    
    - name: Deploy to Railway
      run: |
        npm install -g @railway/cli
        cd backend
        railway link ${{ secrets.RAILWAY_PROJECT_ID }}
        railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
  
  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install Dependencies
      run: |
        npm install
        npm install -D @vitejs/plugin-react-swc
    
    - name: Build
      run: npm run build
      env:
        CI: false
        NODE_ENV: production
        VITE_API_URL: ${{ secrets.VITE_API_URL }}
    
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-args: '--prod'
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./ 